version: '3.8'

services:
  gui-app:
    build:
      context: .
    image: gui-app-image
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=${PULSE_SERVER}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: xeyes
    privileged: true